import type { Metadata } from "next";
import { Happy_Monkey, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const happyMonkey = Happy_Monkey({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`scroll-smooth`}>
      <body className={`${inter.className} ${happyMonkey.className}`}>
        {children}
      </body>
    </html>
  );
}
